short_forms = {
    "asap": "as soon as possible",
    "brb": "be right back",
    "btw": "by the way",
    "idk": "I don't know",
    "imo": "in my opinion",
    "omg": "oh my god",
    "tbh": "to be honest",
    "lol": "laugh out loud",
    "np": "no problem",
    "fyi": "for your information",
    "ttyl": "talk to you later",
    "smh": "shaking my head",
    "bff": "best friends forever",
    "irl": "in real life",
    "afaik": "as far as I know",
    "wtf": "what the fuck",
    "rn": "right now",
    "idc": "I don’t care",
    "gtg": "got to go",
    "nvm": "never mind"
}
